### PR TITLE
New frontpage

### PR DESCRIPTION
**Pull request by cantino**
Preview here: https://cantino.github.io/orbital-index-1/

### CODE REVIEW

**Comment by benlachman** [comment]
Little surprised you merged these without any feedback. The tweaked landing experience doesn’t have as much appeal to me personally… I like to have a visual understanding of what this thing is before I am dumped into some random content that I didn’t actually ask for. But let’s see how it does in analytics for a bit and then decide where we want it to go.

**Comment by cantino** [comment]
I wanted to get it in to see if we get a conversion bump this Tuesday.
Happy to revert changes that we decide not to keep. I thought it was the
set of changes we’d texted about: most recent content on front page so
people know what they’re signing up for, a signup
form, and no popups. (Previously it was 2 clicks before you could see what
you were getting, and 1 to signup.) Let’s see how it does.

BTW, the script is updated to regenerate the front page from the newest
archive so no change to how you add content.

**Comment by benlachman** [comment]
Sounds good. 👌🏼

**Comment by benlachman** [comment]
@cantino I think this broke google analytics actually. It's embedded in the other layouts, but I don't think the new index layout includes it.

**Pull request merged**
